version: '2'
services:
   apiGateway:
    image: "flyingwhale/javaspring:latest"
    ports:
        - "8082:8082"
   postgres:
     image: "postgres:latest"
   raidService:
     image: "flyingwhale/goservice:latest"
     ports:
        - "8080"
   messagebroker:
     image: rabbitmq
     ports:
         - "5671"
         - "5672"
     environment:
       - RABBITMQ_DEFAULT_USER=spring
       - RABBITMQ_DEFAULT_PASS=spring
   rpcserver:
     image: "flyingwhale/jsrabbitserver:latest"
     ports:
        - "5000"
